language: python
python:
    - "3.4"
env:
    - TOXENV=py27
    - TOXENV=py34
install:
    - pip install tox
script:
    - tox
branches:
    only:
        - master
deploy:
    provider: pypi
    user:
        secure: WpS5sfI4i7iKqjulaLecaxL8705DB0uZUT4WoppPSbe1WAwFWkpArHN83/IXDYDgnVnpaVsbT/LqZPAh1sGyiz2i3pF2pfXICiDWlpCq0RPRwr5A3FLAzMSSgYFF5OBupXIkOnXCC0u2CexEchg33LI1+T0RkULCrYtIqqffqEQ=
    password:
        secure: HIvWY8H/cBAwoxofCTYSPIqYALsM0nPggJ/J2gm0FB56QP1+54Rbn0NHxZ6FCrXglhRxl0CMyl/kQ1wXJENlz50h671v9vKkaG0ACIDNxZG7lHNr8bI/KFcf6BwjBWVBCeiRxH9Bg7x11TPVpRgsuOgNkOM7p4s/Q4VP3/DnJTA=
    on:
        tags: true
