language: python
python:
    - "3.4"
env:
    - TOXENV=py27
    - TOXENV=py34
branches:
    except:
        - /^dev-.+$/
install:
    - pip install tox
script:
    - tox
deploy:
    provider: pypi
    user: Christopher.Sang
    password:
        secure: S4ac1FUEV4cnFonK+/mjDHJMIJLDs/FtWhkZPtHIQNkmITi8sfWyp4EoIgK3ujw5lTt22wnAvbUTFSKJRv/HtmTEzz1TRfd6494h3xTYHrjhMJiFWz10y90gUXr1ARraYPmVqVFTAX6TsCviW+FHop8/DRqKNlTzZheglyL+ptM=
    on:
        tags: true
        repo: csdev/datacheck
